Repository Fate-Grand-Automata/FGA, pull requests merged in 2020-04, with the labels that each got.

#1 Autoskill list
  FateGrandAutomata/AutoSkill/AutoSkillActivity.cs
  FateGrandAutomata/AutoSkill/AutoSkillItemActivity.cs
  FateGrandAutomata/AutoSkill/AutoSkillSettingsFragment.cs
  FateGrandAutomata/AutoSkill/ManageAutoSkillSettingsFragment.cs
  FateGrandAutomata/FateGrandAutomata.csproj
  FateGrandAutomata/MainActivity.cs
  FateGrandAutomata/Preferences/FgoPreferences.cs
  FateGrandAutomata/Preferences/FgoSupportPreferences.cs
  FateGrandAutomata/Preferences/RefillSettingsFragment.cs
  FateGrandAutomata/Preferences/SupportSettingsFragment.cs
  FateGrandAutomata/Resources/Resource.designer.cs
  FateGrandAutomata/Resources/drawable/ic_delete.xml
  FateGrandAutomata/Resources/drawable/ic_plus.xml
  FateGrandAutomata/Resources/layout/autoskill_item.xml
  FateGrandAutomata/Resources/layout/autoskill_list.xml
  FateGrandAutomata/Resources/values/preferences.xml
  FateGrandAutomata/Resources/xml/app_preferences.xml
  FateGrandAutomata/Resources/xml/autoskill_item_preferences.xml
  FateGrandAutomata/Resources/xml/autoskill_preferences.xml
  README.md
Labels: enhancement

#2 Notch support
  CoreAutomata/AutomataApi.cs
  CoreAutomata/EntryPoint.cs
  CoreAutomata/GameAreaManager.cs
  CoreAutomata/IPlatformImpl.cs
  CoreAutomata/ScreenshotManager.cs
  CoreAutomata/TransformationExtensions.cs
  FateGrandAutomata/AndroidImpl.cs
  FateGrandAutomata/CutoutManager.cs
  FateGrandAutomata/FateGrandAutomata.csproj
  FateGrandAutomata/MainActivity.cs
  FateGrandAutomata/ScriptRunnerService.cs
  README.md
Labels: enhancement

#4 Fix a null pointer exception on non-cutout devices
  FateGrandAutomata/CutoutManager.cs
Labels: bug

#5 Add foreground service permission
  FateGrandAutomata/Properties/AndroidManifest.xml
Labels: bug

#15 Fix AccessibilityService on force quitting
  FateGrandAutomata/ScriptRunnerService.cs
Labels: bug

#13 Card priority drag list
  FateGrandAutomata.Core/Modules/Card.cs
  FateGrandAutomata/CardPriorityActivity.cs
  FateGrandAutomata/DraggableRecyclerView/IItemTouchHelperAdapter.cs
  FateGrandAutomata/DraggableRecyclerView/IItemTouchHelperViewHolder.cs
  FateGrandAutomata/DraggableRecyclerView/IOnStartDragListener.cs
  FateGrandAutomata/DraggableRecyclerView/ItemTouchHelperCallback.cs
  FateGrandAutomata/DraggableRecyclerView/ItemViewHolder.cs
  FateGrandAutomata/DraggableRecyclerView/RecyclerListAdapter.cs
  FateGrandAutomata/FateGrandAutomata.csproj
  FateGrandAutomata/Preferences/FgoPreferences.cs
  FateGrandAutomata/Preferences/SettingsFragment.cs
  FateGrandAutomata/Resources/Resource.designer.cs
  FateGrandAutomata/Resources/drawable/ic_hamburger.xml
  FateGrandAutomata/Resources/layout/autoskill_item.xml
  FateGrandAutomata/Resources/layout/card_priority.xml
  FateGrandAutomata/Resources/layout/card_priority_item.xml
  FateGrandAutomata/Resources/values/colors.xml
  FateGrandAutomata/Resources/values/strings.xml
  FateGrandAutomata/Resources/xml/app_preferences.xml
  README.md
Labels: enhancement

#16 Movable Play button
  CoreAutomata/ComparableExtensions.cs
  FateGrandAutomata/ScriptRunnerService.cs
Labels: enhancement

#9 Preferred Servant/CE pick from list
  CoreAutomata/AutomataApi.cs
  CoreAutomata/IPlatformImpl.cs
  FateGrandAutomata.Core/ImageLocator.cs
  FateGrandAutomata.Core/Modules/Support.cs
  FateGrandAutomata.Core/SupportImageMaker.cs
  FateGrandAutomata.Core/images/Support/ce/aerial_drive.png
  FateGrandAutomata.Core/images/Support/ce/blackgrail.png
  FateGrandAutomata.Core/images/Support/ce/chaldea_lunchtime.png
  FateGrandAutomata.Core/images/Support/ce/golden_sumo_boulder_tournament.png
  FateGrandAutomata.Core/images/Support/ce/gudaguda_poster_girl.png
  FateGrandAutomata.Core/images/Support/ce/holy_night_supper.png
  FateGrandAutomata.Core/images/Support/ce/mona_lisa.png
  FateGrandAutomata.Core/images/Support/ce/teatime.png
  FateGrandAutomata.Core/images/Support/servant/Merlin/merlin1.png
  FateGrandAutomata.Core/images/Support/servant/Merlin/merlin23.png
  FateGrandAutomata.Core/images/Support/servant/Merlin/merlin4.png
  FateGrandAutomata.Core/images/Support/servant/Merlin/merlin_c.png
  FateGrandAutomata.Core/images/Support/servant/Skadi/skadi1.png
  FateGrandAutomata.Core/images/Support/servant/Skadi/skadi2.png
  FateGrandAutomata.Core/images/Support/servant/Skadi/skadi3.png
  FateGrandAutomata.Core/images/Support/servant/Skadi/skadi4.png
  FateGrandAutomata.Core/images/Support/servant/Waver/waver1.png
  FateGrandAutomata.Core/images/Support/servant/Waver/waver2.png
  FateGrandAutomata.Core/images/Support/servant/Waver/waver3.png
  FateGrandAutomata.Core/images/Support/servant/Waver/waver4.png
  FateGrandAutomata/AndroidImpl.cs
  FateGrandAutomata/AutoSkill/AutoSkillSettingsFragment.cs
  FateGrandAutomata/AutoSkill/MultiSelectListSummaryProvider.cs
  FateGrandAutomata/FateGrandAutomata.csproj
  FateGrandAutomata/MainActivity.cs
  FateGrandAutomata/Preferences/FgoPreferences.cs
  FateGrandAutomata/Preferences/FgoSupportPreferences.cs
  FateGrandAutomata/Preferences/SupportSettingsFragment.cs
  FateGrandAutomata/Properties/AndroidManifest.xml
  FateGrandAutomata/Resources/Resource.designer.cs
  FateGrandAutomata/Resources/drawable/ic_clear.xml
  FateGrandAutomata/Resources/layout/content_main.xml
  FateGrandAutomata/Resources/menu/menu_main.xml
  FateGrandAutomata/Resources/values/preferences.xml
  FateGrandAutomata/Resources/xml/autoskill_item_preferences.xml
  FateGrandAutomata/Resources/xml/support_preferences.xml
  README.md
Labels: enhancement

#19 GitHub Actions CI workflow
  .github/workflows/ci.yml
  FateGrandAutomata.sln
  FateGrandAutomata/fgautomata.keystore.gpg
Labels: enhancement

#24 Fix reading refill repetitions
  FateGrandAutomata/Preferences/FgoRefillPreferences.cs
Labels: bug

#21 Create a .nomedia file when the support folder is created
  FateGrandAutomata.Core/ImageLocator.cs
Labels: enhancement

#26 Fix Autoskill selected item not displaying correctly
  FateGrandAutomata/AutoSkill/AutoSkillActivity.cs
  FateGrandAutomata/AutoSkill/AutoSkillSettingsFragment.cs
  FateGrandAutomata/AutoSkill/ManageAutoSkillSettingsFragment.cs
Labels: bug

#30 Ignore Notch calculation option
  CoreAutomata/ComparableExtensions.cs
  CoreAutomata/GameAreaManager.cs
  CoreAutomata/Location.cs
  CoreAutomata/Region.cs
  CoreAutomata/Size.cs
  FateGrandAutomata.Core/Modules/Battle.cs
  FateGrandAutomata.Core/Modules/Scaling.cs
  FateGrandAutomata.Core/Preferences/IFgoPreferences.cs
  FateGrandAutomata/CutoutManager.cs
  FateGrandAutomata/DroidCvPattern.cs
  FateGrandAutomata/Preferences/FgoPreferences.cs
  FateGrandAutomata/Resources/Resource.designer.cs
  FateGrandAutomata/Resources/values/preferences.xml
  FateGrandAutomata/Resources/xml/app_preferences.xml
  FateGrandAutomata/ScriptRunnerService.cs
Labels: bug, enhancement

#32 Fix: Autosupport scrolling too far
  FateGrandAutomata/AndroidImpl.cs
  FateGrandAutomata/AndroidImplGestures.cs
  FateGrandAutomata/FateGrandAutomata.csproj
  FateGrandAutomata/GestureCompletedCallback.cs
Labels: bug

#37 Fix: Preferred Servant/CE not falling back to ones set in Support menu when Autoskill is used and Preferred Servant/CE are not set in the selected configuration
  FateGrandAutomata/Preferences/FgoSupportPreferences.cs
Labels: bug

#45 Consistent Default Card Priority
  FateGrandAutomata/CardPriorityActivity.cs
  FateGrandAutomata/Preferences/FgoPreferences.cs
  FateGrandAutomata/Preferences/MoreSettingsFragment.cs
Labels: bug

#46 Add Issue templates and Samsung troubleshooting doc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  README.md
  SAMSUNG.md
Labels: documentation

#62 Wait after Gesture has finished
  FateGrandAutomata.Core/Modules/Game.cs
  FateGrandAutomata.Core/images/Support/ce/kaleidoscope.png
  FateGrandAutomata/AndroidImplGestures.cs
Labels: bug

#74 Allow NP usage after executing commands
  FateGrandAutomata.Core/Modules/AutoSkill.cs
Labels: bug

#76 Add Boost Item Selection Mode: Skip
  FateGrandAutomata.Core/AutoBattle.cs
  FateGrandAutomata.Core/Preferences/IFgoPreferences.cs
  FateGrandAutomata/Preferences/FgoPreferences.cs
  FateGrandAutomata/Resources/values/arrays.xml
  FateGrandAutomata/Resources/values/preferences.xml
  FateGrandAutomata/Resources/xml/app_preferences.xml
Labels: bug

#81 Fix: Order change still skipping skills
  FateGrandAutomata.Core/Modules/AutoSkill.cs
Labels: bug

#79 Close Extra info window after Targeted skill
  FateGrandAutomata.Core/Modules/AutoSkill.cs
Labels: bug, enhancement

#83 Sort Autoskill items alphabetically
  FateGrandAutomata/AutoSkill/AutoSkillActivity.cs
  FateGrandAutomata/AutoSkill/ManageAutoSkillSettingsFragment.cs
Labels: enhancement
